name: pom
version: git
summary: Advanced Pomodoro timer with CLI and Web UI
description: |
  Advanced Pomodoro timer featuring AI insights, multi-profiles, cloud sync,
  and plugin system. Includes both CLI and modern web interface.

grade: stable
confinement: strict
base: core22

apps:
  pom:
    command: bin/pom
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - desktop-notification

parts:
  pom:
    plugin: go
    source: .
    build-snaps:
      - go/1.21/stable
      - node/18/stable
    override-build: |
      cd web/frontend
      npm install
      npm run build
      cd ../..
      go build -ldflags "-s -w" -o $SNAPCRAFT_PART_INSTALL/bin/pom .