name: pom
base: core22
version: '1.0.0'
summary: A feature-rich command-line Pomodoro timer
description: |
  A command-line Pomodoro timer that helps you stay focused and productive.
  Features include:
  * Live countdown timer
  * Desktop notifications
  * Sound alerts
  * Session statistics
  * Configurable work/break durations
  * Pause/resume functionality

grade: stable
confinement: strict

apps:
  pom:
    command: bin/pom
    plugs:
      - desktop
      - audio-playback
      - unity7

parts:
  pom:
    plugin: go
    source: .
    build-snaps:
      - go
    stage-packages:
      - libnotify-bin
      - pulseaudio-utils
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/man/man1
      cp packaging/man/pom.1 $CRAFT_PART_INSTALL/usr/share/man/man1/
      gzip -f $CRAFT_PART_INSTALL/usr/share/man/man1/pom.1 