name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deb-package:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts

      - name: Build DEB package
        run: |
          cd packaging/deb
          dpkg-buildpackage -b -us -uc
          
      - name: Upload DEB package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: packaging/*.deb

  snap-package:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Snap package
        uses: snapcore/action-build@v1
        with:
          path: packaging/snap
          
      - name: Upload Snap package
        uses: actions/upload-artifact@v3
        with:
          name: snap-package
          path: packaging/snap/*.snap
          
      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: packaging/snap/*.snap
          release: stable

  flatpak-package:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          
      - name: Build Flatpak package
        run: |
          flatpak-builder --repo=repo build-dir packaging/flatpak/com.github.flack.pom.yml
          flatpak build-bundle repo pom.flatpak com.github.flack.pom
          
      - name: Upload Flatpak package
        uses: actions/upload-artifact@v3
        with:
          name: flatpak-package
          path: pom.flatpak

  aur-publish:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v3
      
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: pom
          pkgbuild: packaging/arch/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          
  rpm-package:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v3
      
      - name: Install RPM build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          
      - name: Build RPM package
        run: |
          cd packaging/rpm
          rpmbuild -bb pom.spec
          
      - name: Upload RPM package
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package
          path: packaging/rpm/RPMS/x86_64/*.rpm

  publish-packages:
    runs-on: ubuntu-latest
    needs: [deb-package, snap-package, flatpak-package, rpm-package]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deb-package/*.deb
            snap-package/*.snap
            flatpak-package/*.flatpak
            rpm-package/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 